### ISSUE TITLE
Add Option to Request Bluetooth Permission on iOS Without Triggering Dialog

### ISSUE THREAD

**Issue by gchallen** [Estimote/react-native-proximity#12]
I'd like to navigate my users to a special screen before prompting them for the location permission on iOS. However, at this point the `requestLocationPermission` method on iOS returns the location status if the request has been made but prompts if it has not been made. So there is no way to know whether or not this method will prompt the user or not when it is run.

Obviously a workaround is to just use another React Native permission library, and I may try that. But if this is not hard to add it would be convenient to include: both for Android and iOS. (Although Android is easily supported by the existing `AndroidPermission` library.)

**Comment by heypiotr** [comment]
Agreed that this would be convenient, thanks for the suggestion!

**Comment by gchallen** [comment]
Related: is the latest version of the SDK triggering a location request after install on iOS? I'm seeing a new one that doesn't seem to have triggered by my app...

**Comment by gchallen** [comment]
Right—sorry. I realized later that I was starting the observer accidentally before I wanted to, which triggered the popup.
