### ISSUE TITLE
Exception error when running on iOS

### ISSUE THREAD

**Issue by udameli** [Estimote/react-native-proximity#15]
Hi! I am experiencing issues when running my project on iOS. I get the following error:

> ExceptionsManager.js:84
> 
>  Exception '-[EPXProximityObserver initWithCredentials:errorBlock:]: unrecognized selector sent to instance 0x60c000010940' was thrown while invoking initialize on target RNEstimoteProximity with params (
>         {
>         appId = "my-app-id";
>         appToken = my-app-token;
>         notification =         {
>             text = "We'll notify you when you're next to something interesting.";
>             title = "Exploration mode is on";
>         };
>     }
> )
> callstack: (
> 	0   CoreFoundation                      0x0000000108aa61e6 __exceptionPreprocess + 294
> 	1   libobjc.A.dylib                     0x0000000107391031 objc_exception_throw + 48
> 	2   CoreFoundation                      0x0000000108b27784 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
> 	3   CoreFoundation                      0x0000000108a28898 ___forwarding___ + 1432
> 	4   CoreFoundation                      0x0000000108a28278 _CF_forwarding_prep_0 + 120
> 	5   HMExperiment                        0x000000010666c35a -[RNEstimoteProximity initialize:] + 314
> 	6   CoreFoundation                      0x0000000108a29ccc __invoking___ + 140
> 	7   CoreFoundation                      0x0000000108a29b84 -[NSInvocation invoke] + 308
> 	8   CoreFoundation                      0x0000000108a428d6 -[NSInvocation invokeWithTarget:] + 54
> 	9   HMExperiment                        0x00000001064371fc -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2796
> 	10  HMExperiment                        0x00000001064ed242 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 786
> 	11  HMExperiment                        0x00000001064ecd6f _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 127
> 	12  HMExperiment                        0x00000001064ecce9 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 25
> 	13  libdispatch.dylib                   0x000000010ed4373b _dispatch_call_block_and_release + 12
> 	14  libdispatch.dylib                   0x000000010ed44779 _dispatch_client_callout + 8
> 	15  libdispatch.dylib                   0x000000010ed4e778 _dispatch_main_queue_callback_4CF + 1279
> 	16  CoreFoundation                      0x0000000108a68c99 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
> 	17  CoreFoundation                      0x0000000108a2cea6 __CFRunLoopRun + 2342
> 	18  CoreFoundation                      0x0000000108a2c30b CFRunLoopRunSpecific + 635
> 	19  GraphicsServices                    0x000000010c2bea73 GSEventRunModal + 62
> 	20  UIKit                               0x000000010c7ca0b7 UIApplicationMain + 159
> 	21  HMExperiment                        0x000000010637e91f main + 111
> 	22  libdyld.dylib                       0x000000010edb9955 start + 1
> )

I've built the project using `react-native init`. It works fine for Android but throws the exception for iOS. The proximity observer was initialized similarly to what was shown in the example app.

Below is the content of package.json

```
{
  "name": "HMExperiment",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@estimote/react-native-proximity": "0.3.2",
    "react": "^16.4.1",
    "react-native": "^0.56.0",
    "react-native-network-info": "^3.2.2",
    "react-native-radar": "^2.0.1",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-actions": "^2.6.1",
    "redux-saga": "^0.16.0"
  },
  "devDependencies": {
    "babel-jest": "23.4.2",
    "babel-preset-react-native": "^5",
    "jest": "23.4.2",
    "react-test-renderer": "16.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by heypiotr** [comment]
You probably have a mismatch between the `react-native-proximity` plugin version, and the `EstimoteProximitySDK` native-iOS-SDK version.

If you want to stay on `"@estimote/react-native-proximity": "0.3.2"`, then you need the native-SDK version 0.14.0. (In your Podfile: `pod 'EstimoteProximitySDK', '0.14.0'`, then `pod update`.)

But I'd recommend updating to the latest version, 0.4.0, and then you need the native-SDK version 1.0. (In your Podfile: `pod 'EstimoteProximitySDK', '~> 1.0'`, then `pod update`.)

Your issue report is actually pretty revealing—the need to maintain the correct matching is probably quite a pain-point, so I'll try to experiment with bundling the native-SDK directly with the plugin. Then that burden is on the maintainers of this plugin, not on the users, as it should be (: Thanks a ton!

**Comment by udameli** [comment]
Thanks for your help @heypiotr ! It works now :)
