### ISSUE TITLE
ios attachments object is empty

### ISSUE THREAD

**Issue by timsatterfield** [Estimote/react-native-proximity#2]
Using the example app, but updated index.js with just one zone for simplicity sake.
```
const zone1 = new RNEP.ProximityZone(2, 'vendor', 'foocorp')

zone1.onChangeAction = (attachments) => {
  console.log('zone1 onChange', attachments)
}
```

The beacons belonging to the app_id are configured with two attachments: 'vendor' and 'room'.  Vendor is the filter, and room is extra info we want to know about the beacon.

Looking through xcode logs, I can see that RNEstimoteProximity module does find the beacons and the full attachment data. However the logging from the react-native app layer, shows only the identifier and an empty attachment object.

```
2018-05-30 19:41:04.818 [info][tid:main][RNEstimoteProximity.m:96] onChangeAction, zoneId = 8xb04j855fw, attachments = {(
    [EPXProximityDeviceAttachment] identifier = 68af07cf38efbc052f115fa2e1af3e0b, payload = {"room":"2000","vendor":"foocorp"},
    [EPXProximityDeviceAttachment] identifier = a48e89df5b17437cf5570b2cc22d6109, payload = {"room":"1001","vendor":"foocorp"},
    [EPXProximityDeviceAttachment] identifier = 8b32b83b39612bd1007c80296b177233, payload = {"room":"3000","vendor":"foocorp"}
)}
2018-05-30 19:41:04.821 [info][tid:com.facebook.react.JavaScript] 'zone1 onChange', [ { deviceIdentifier: '68af07cf38efbc052f115fa2e1af3e0b',
    payload: {} },
  { deviceIdentifier: 'a48e89df5b17437cf5570b2cc22d6109',
    payload: {} },
  { deviceIdentifier: '8b32b83b39612bd1007c80296b177233',
    payload: {} } ]
```

This is specific to ios

**Comment by heypiotr** [comment]
I looked into this and it appears to be just a “visual” bug. As in, the payload is actually a JavaScript `Map` object, and when I call “get” on it with the appropriate key, I get the value—even though it doesn’t appear with console.log in Xcode console. (As a side note, it appears just fine in Chrome dev console.)

This is definitely confusing though, so I’ll leave the issue open for now, and maybe change the code of the example to be more explicit about the fact that this is a Map.

**Comment by timsatterfield** [comment]
Thanks for the update. I can confirm that I can access the attachments.  But yes this was really confusing.
