### ISSUE TITLE
Background Support Limitations

### ISSUE THREAD

**Issue by thchia** [Estimote/react-native-proximity#22]
I've just ordered a set of Proximity Beacons to play with, and while I wait for them I have a question:

Is it within the scope of this library to handle Notification Actions? For example;

1. A user moves into range of a beacon;
2. They receive a notification on their device;
3. They can perform the appropriate action to engage in an action from the notification (e.g. force touch).

Is this something that can be achieved (e.g. with [react-native-notifications](https://github.com/wix/react-native-notifications))?

**Comment by heypiotr** [comment]
This library will let you know via a callback when you enter/exit range of your beacons. What action you take in response, and how, that is up to you (: 

If you want to show a notification, you can e.g. use the PushNotificationIOS component that's built into react-native, specifically its `presentLocalNotification` method. (https://facebook.github.io/react-native/docs/pushnotificationios#presentLocalNotification). Or use another library you like best. (I don't have a lot of experience with react-native, so can't really recommend anything, you could ask around on some react-native forums/communities.)

Now, "never say never", but I don't think there's any reason for our proximity library to implement its own notifications API, when there's already many other good options for that out there.
