### ISSUE TITLE
Xcode successfully builds .xcworkspace but throws error: dyld`__abort_with_payload:

### ISSUE THREAD

**Issue by irajwani** [Estimote/react-native-proximity#23]
Hi folks, I'm a noob when it comes to opening issues, so please bear with me. 

I followed the steps outlined in the README to integrate react-native-proximity within my react native project application. The application builds successfully but gets stuck at the launcscreen.xib image when the app starts on my phone (which Im using as the simulator) and doesn't progres forward to the classic red screen or 'downloading javascript bundle' phase. Simultaneously, in Xcode, it shows the following error:
![screen shot 2018-10-02 at 12 08 01 pm](https://user-images.githubusercontent.com/25965881/46334579-0e994d80-c63e-11e8-8e7e-4bedd0d2587e.png)

Here's my Podfile:
![screen shot 2018-10-02 at 12 08 19 pm](https://user-images.githubusercontent.com/25965881/46334745-af880880-c63e-11e8-8f97-a1c5c71a10c9.png)

And here's my package.json:
![screen shot 2018-10-02 at 12 29 29 pm](https://user-images.githubusercontent.com/25965881/46334800-dd6d4d00-c63e-11e8-8002-3bb2508ba719.png)

And yes, my iPhone developer certificates in KeyChain Access are using system defaults under 'Trust' as opposed to always trust.
Again, I definitely followed all the steps, and cross-referenced them against the [basic iOS setup](https://developer.estimote.com/proximity/ios-tutorial/) really need to get my react native project working with my estimote proximity beacons as I have a deadline. So any help whatsoever would be greatly appreciated.

**Comment by heypiotr** [comment]
Thanks for such a detailed bug report! ❤️ 

Xcode 10 shipped last week with Swift 4.2, which required us to release an updated version of the iOS Proximity SDK built for Swift 4.2. (There are binary-interface incompatible changes between Swift 4.1 and Swift 4.2.)

So, you probably just need to run `pod update` in your `ios` directory to update to the latest version of the native SDK, 1.2.0. Let us know if that helps.

**Comment by irajwani** [comment]
YESSS, it worked. 
![screen shot 2018-10-05 at 4 26 12 am](https://user-images.githubusercontent.com/25965881/46508583-87272680-c857-11e8-8647-4cb9af7c3486.png)

You're a life saver. The delay in reply was because xcode 10 broke my react native project, so I had to manually fix it by going through some terminal stuff to build the application each time. But yes, `pod update`  did the trick. Side question, and your company's docs probably answer this, but can one check when two proximity beacons are super close to each other as opposed to just checking when my phone is close to N number of beacons. That is, can we check if, say, 2 beacons are in/not in each other's proximity and then let the phone know?

**Comment by heypiotr** [comment]
Glad to heart that! ❤️ 

>can we check if, say, 2 beacons are in/not in each other's proximity and then let the phone know?

The Proximity Beacons only broadcast, and don't listen/scan, so they wouldn't know on their own when they're close to each other.

Our new/upcoming [LTE Beacon](https://blog.estimote.com/post/177348177680/estimote-lte-m-beacon) is programmable via JavaScript, and can be programmed to scan for other Bluetooth devices, so 2 LTE Beacons could technically know when they're close to each other, and broadcast that information over Bluetooth to the smartphone. (Caveat: continuous Bluetooth scanning will drain the battery much faster, so the LTE Beacon would need to be recharged often, it has a rechargeable battery and a USB-C port for that.)
