### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by tomtomgo92** [Estimote/react-native-proximity#25]
Hello I think have problem with SDK I have this error when I want compile

```
MacOS  10.14.2 (18C38b)
react-native-cli: 2.0.1
Xcode Version 10.1 (10B61)
```

```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/containers/Bundle/Application/264F88BB-4DF5-4EF9-8152-7ABEF75F846F/mca.app/Frameworks/EstimoteProximitySDK.framework/EstimoteProximitySDK
  Reason: image not found
(lldb) 
```

Could you please advise ?

Thank you in advance :)

**Comment by heypiotr** [comment]
You need to enable "Always Embed Swift in Standard Libraries" in the Xcode project's Build Settings. 

This is mentioned in the README, in the "Installation", "On iOS, you also need to:", point 2. Easy to miss, so no worries (:

**Comment by tomtomgo92** [comment]
Thank :)
