### ISSUE TITLE
can't build for android apk

### ISSUE THREAD

**Issue by i-sattaya** [Estimote/react-native-proximity#26]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':@estimote_react-native-proximity'.
> Could not resolve all artifacts for configuration ':@estimote_react-native-proximity:classpath'.
   > Could not find com.android.tools.build:gradle:2.2.3.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.jar
     Required by:
         project :@estimote_react-native-proximity

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by troianoandres** [comment]
I did not tested it but this error was removed if the version is updated and/or a repository is added. I will test it out probably today or tomorrow and will raise a pr so we can check it out if wanted

**Comment by i-sattaya** [comment]
i think have to update "@Estimote/react-native-proximity" for react-native last version (0.57.5)

**Comment by heypiotr** [comment]
>Could not find com.android.tools.build:gradle:2.2.3.
>Searched in the following locations:
>https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.pom
>https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.jar

Mhm, this doesn't make much sense to me, I can see these files are in fact available for download at these URLs.

Does the "example" bundled in this repo work for you? Last time I tested it in late October, it worked fine. It uses react-native 0.57.4 though.

**Comment by heypiotr** [comment]
If you happen to know what caused the problem or managed to solve it somehow, feel free to share for any future generations 😃. If the problem persists, let me know and I'll re-open this issue.
