### ISSUE TITLE
How create Alert ?

### ISSUE THREAD

**Issue by tomtomgo92** [Estimote/react-native-proximity#29]
How create alert when I come to perimeter of Estimote?

Do you have a better doc for react native Estimote proximity ? 😅 about range, setting...

**Comment by troianoandres** [comment]
I’m guessing based on what I remember. You have a watcher so when the change is triggered you should do some react native logic to do what you want. The library is only to let you know when the context has changed the rest is your code. But wait for a collaborator response, I’m just guessing based on what I rember

**Comment by tomtomgo92** [comment]
Thanck @troianoandres but my context stay `undefined`  maybe i'm not connected :')
