### ISSUE TITLE
Fetching tags from Cloud failed

### ISSUE THREAD

**Issue by carlosa54** [Estimote/react-native-proximity#30]
I'm getting this error while using my estimote credentials on my app running with the simulator.

`Proximity Observer error: Error Domain=EPXProximityObserverErrorDomain Code=1 "Fetching tags from Cloud failed." UserInfo={NSUnderlyingError=0x6000024a4780 {Error Domain=EstimoteProximitySDK.PersistentTagsRepository.Error Code=2 "When running offline, internet connection is required when starting the observer for the first time."}, NSLocalizedDescription=Fetching tags from Cloud failed., NSLocalizedRecoverySuggestion=Make sure your cloud credentials are correct and you have a valid internet connection. See CloudCredentials for more.}`

This is happening using the example app of this repo as well, confirmed that the phone has internet and there's tags on my estimote cloud account.

**Comment by carlosa54** [comment]
Worked after generating a tag with more than 8 characters.

**Comment by ishaqashraf** [comment]
@carlosa54  i am getting this error . i updated my tags like this '918-zxcvbnmasdasd' . still getting the same error .

**Comment by jeffyamada** [comment]
I'm also having this issue. @ishaqashraf did you figure it out?

**Comment by ishaqashraf** [comment]
yes i was getting the error because the array which i am passing in proximate is null that'w why it showing me error , before start observer console the payload which you have set and check if the array length is 0 or not .
