### ISSUE TITLE
IOS App Store rejection on using bluetooth-central in the UIBackgroundModes key in Info.plist

### ISSUE THREAD

**Issue by ohmadmin** [Estimote/react-native-proximity#32]
i am using https://github.com/Estimote/react-native-proximity library for my react native mobile app and use estimote beacon for detecting customer entry.
App store rejected my ios app stating the following reason. is there any workaround for this? anyone faced this problem before and how do i resolve this?

Reason:
Your app declares support for bluetooth-central in the UIBackgroundModes key in your Info.plist but does not provide Bluetooth Low Energy functionality. The Bluetooth Background modes are for apps that communicate to other devices using Bluetooth Low Energy and the Core Bluetooth framework.

Next Steps

To resolve this issue, please revise your app to add support for Bluetooth Low Energy communication through Core Bluetooth in your app or remove the bluetooth- values from the UIBackgroundModes key.

Resources

For more information on Core Bluetooth, please review the Core Bluetooth Framework Reference.

**Comment by heypiotr** [comment]
Explained/discussed here:

https://forums.estimote.com/t/ios-app-store-rejection-on-using-bluetooth-central-in-the-uibackgroundmodes-key-in-info-plist/9624/2?u=heypiotr

I also added a note about it to the README, in the Background Support section:

>**Note**: Background Modes undergo extra scrutiny during App Store review. If you're submitting your app to the App Store, we recommend proactively explaining in the notes why/how your app uses Bluetooth in the background.
