### ISSUE TITLE
Library not loaded error. when running in iOS.

### ISSUE THREAD

**Issue by cfmitrah** [Estimote/react-native-proximity#37]
react-native: 0.59.5
@estimote/react-native-proximity: 0.5.0

I followed the linking instructions in the docs. but when building the app in iOS. the build succeeds, the metro bundler doesn't progress and the below message is displayed in logs.
```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/Apple/Library/Developer/CoreSimulator/Devices/78911C19-B938-43F9-B3D7-C70CF4BCC190/data/Containers/Bundle/Application/5532CB3F-5734-48F4-9D8B-59807A8A6EC3/estimotesample.app/Frameworks/EstimoteProximitySDK.framework/EstimoteProximitySDK
  Reason: image not found
```

I have already enabled "Always Embed Swift in Standard Libraries" in the Xcode project's Build Settings.

X-code version - 10.0

**Comment by cfmitrah** [comment]
FYI i have already  enabled "Always Embed Swift in Standard Libraries" in the Xcode project's Build Settings.

**Comment by nicolascanto** [comment]
hello, some solution?

**Comment by cfmitrah** [comment]
@heypiotr Please help me with this issue. I'm stuck at this for more than two days.

**Comment by heypiotr** [comment]
I couldn't reproduce this on a fresh 0.59.5 and following the installation instructions—worked for me. Although I'm on Xcode 10.2.

Can you show me a screenshot with your "Always Embed Swift in Standard Libraries" config? With this error, 99% of the time there's something wrong in there.

**Comment by cfmitrah** [comment]
It even occurs in the example project included in this package
![estimote1](https://user-images.githubusercontent.com/532401/57370162-11988580-71ad-11e9-9168-4dae58877f0b.PNG)
![estimoteissue](https://user-images.githubusercontent.com/532401/57370172-16f5d000-71ad-11e9-8d64-bc413b6da89e.PNG)

**Comment by cfmitrah** [comment]
It is fixed. Thank you!

**Comment by heypiotr** [comment]
Glad to hear that! (:
