### ISSUE TITLE
Android doesn't compile

### ISSUE THREAD

**Issue by milesmatthias** [Estimote/react-native-proximity#4]
```
{app_root}/node_modules/@estimote/react-native-proximity/android/src/main/java/com/estimote/react/RNEstimoteProximityModule.java:8: error: cannot find symbol import com.estimote.proximity_sdk.proximity.ProximityAttachment;
```

iOS works fine. Android fails to build with this error. Latest RN.

**Comment by heypiotr** [comment]
Thanks for the heads up! Looks like our Android team released a new version of the Android Proximity SDK, 0.6.0, with some breaking API changes. (We're still fine-tuning the API before the 1.0 release.)

For now, I've just hard-coded the React Native wrapper to use the 0.5.1. We'll update the wrapper for 0.6.0 at a later date.
