### ISSUE TITLE
RNEP.locationPermission.request() no longer allows users to select Always on iOS 13

### ISSUE THREAD

**Issue by chrisspankroy** [Estimote/react-native-proximity#43]
Users do not have the option to select the "Always" location permission on iOS 13. They can still go into Settings and manually enable it, but the request dialog does not give them the option to select it in-app.

This might be a problem with the native code. Creating an empty native project that requests Always permission also does not give users the option to select Always

**Comment by heypiotr** [comment]
The "always" option will now show up when the app wants to access the location for the first time in the background. The docs are still unclear to me whether this will need some action from the developer, or if this will happen automatically. I'll be trying out the beta when I have a moment to figure this out.

![image](https://user-images.githubusercontent.com/1155764/58944322-e2f8d500-8781-11e9-957c-ce947976320c.png)

**Comment by chrisspankroy** [comment]
AFAIK those dialogs take some time to pop up right (~24 hours)? I agree that the docs are rather unclear about this, but wouldn't this break apps that rely on always having access to the user's location until this dialog pops up? Sure users can go in to Settings and manually change it, but users are never actually going to do that

**Comment by heypiotr** [comment]
I was watching the "what's new in Core Location" stream yesterday, and boy, this change feels unnecessarily complicated.

They said that the app which requests "always" should continue running under the assumption that it has the access (e.g., start monitoring for beacons), and when the first background event is supposed to come, they OS will withhold it and schedule a popup to be shown to the user at the next opportunity. If the user agrees, they will deliver the event, except if they decide that the event is now stale :scream:. And then it all starts working as normal.

If the user disagrees, the app will be let known that the authorization changed from "always" to "when in use".

I've been playing around with the beta yesterday, and I was unable to get the popup to trigger, or get iBeacon monitoring to work in the background at all, even when I manually switched the app to always. So I guess things might be a bit broken right now. I will continue my tests today.

**Comment by chrisspankroy** [comment]
For what it's worth, I've had the 13 beta on my iPhone since Monday night, and I'm just now getting popups for "Always" location access to most of my apps (I got about 10 in a row within about 20 minutes)

**Comment by farzd** [comment]
any updates?

**Comment by heypiotr** [comment]
Since this behavior is "the new normal" on iOS 13, I'll close this issue as not related to the plugin.

Basically, the plugin (or specifically, the Estimote Proximity SDK) still requests the "always" permission, but the flow works differently in iOS 13. So it'll be up to the OS and the user to eventually grant the upgrade from "only when using the app" to "always".
