### ISSUE TITLE
App crashes on iPhone using Xcode Version 11.3.1 

### ISSUE THREAD

**Issue by stewartduffy** [Estimote/react-native-proximity#58]
When using the example app and trying to run on iPhone (using Xcode Version 11.3.1). When the app builds and copies to the device it crashes when trying to load the app.

I have set up device signing & included swift libraries. No luck.

I have tried both the example app and my own app following the installation guide and same result.

Any help would be much appreciated!

**Comment by stewartduffy** [comment]
Anyone?

**Comment by ThijmenDeValk** [comment]
Are you using a free developer account? Apple broke most libraries with iOS 13.3.1 for free developer accounts. It seems to be fixed with 13.4 (but haven't personally tested that yet).

**Comment by stewartduffy** [comment]
Oh yeah, it is a free account.  Ok cool well I am upgrading now. Will I need an xcode upgrade too?

**Comment by ThijmenDeValk** [comment]
Yes, once your iPhone is on 13.4 _and_ Xcode is updated to 11.4, you should be all set!

**Comment by stewartduffy** [comment]
Awesome thanks!

**Comment by stewartduffy** [comment]
This worked a charm thanks.
