### ISSUE TITLE
Failing to build & run on Android

### ISSUE THREAD

**Issue by prism-dan** [Estimote/react-native-proximity#63]
### Issue:

I get the following errors when trying to run on Android (both emulator and tethered physical devices) using `react-native run-android`:

```
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.estimote:proximity-sdk:1.0.5.
     Required by:
         project :app > project :estimote_react-native-proximity
   > Could not find com.estimote:scanning-plugin:0.25.4.
     Required by:
         project :app > project :estimote_react-native-proximity
```

### Environment:

- react-native-proximity: 1.0.5
- react-native: 0.66.4

**Note:** This has worked previously on another app using the exact same version of react-native-proximity, however this doesn't appear to be an issue with the RN version as it build fine on iOS and the issue is related directly to resolving versions during the build phase.

### Things I've already tried:

- Reinstalling the package.
- Wiping & reinstalling node_modules & Pods.
- Clearing the project gradle cache.
- Clearing the global gradle cache.

**Comment by prism-dan** [comment]
Fixed by adding `jcenter()` to the `android/build.gradle` repositories:

```
buildscript {
    // ...
    repositories {
        // ...
        jcenter()
    }
}

// ...
allprojects {
    // ...
    repositories {
        // ...
        jcenter()
    }
}
```

**Comment by thanhnvpk01168** [comment]
Hi @prism-dan 
I also got the same error, how you fixed it.
thanks in advance

**Comment by prism-dan** [comment]
> Hi @prism-dan I also got the same error, how you fixed it. thanks in advance

@thanhnvpk01168 My `build.gradle` (located in the `./android` directory of the  project) was missing `jcenter()` from both buildscript and allprojects repositories groups.

If you locate that file and add `jcenter()` in both locations as I have above that might work.
